[embedding]
    json  = "/Users/load/code/python/model/model-y1-test2/model-symbol.json"
    param = "/Users/load/code/python/model/model-y1-test2/model-0000.params"
[shape]
    width   = 112
    height  = 112
    channel = 3
    output_feature  = 128
[vectdb]
    path = "vectdb"
    dot_distance_threshold = 0.6