[tracker]
	config_file = "staple.yaml"
	wisdom_file = "wisdom"
	disappear_threshold = 100	  
[detect]
	mtccn_model_path = "../models/ncnn"
	mtcnn_threshold     = [0.6,0.7,0.8]
	mtcnn_nms_threshold = [0.7,0.7,0.7]	
	period = 25
	min_score = 1
[db]
	ip = "172.19.0.105"
	port = 9000
[global]
	pnp_config = "3dpnp.toml"
	mxmodel_config = "mxModel.toml"