[embedding]
    infer_mode = "service"
    url = "http://172.19.0.15:81/r100/predict"
    n_sample_count_type1 = 3
    n_sample_count_type2 = 3    
[age]
    enable = true
    n_age_sample = 3
    infer_mode = "service"
    url = "http://172.19.0.15:81/ga/predict" 
[shape]
    width   = 112
    height  = 112
    channel = 3
[vector]
    sim_threshold = 0.4
    merge_threshold = 0.8
    append_threshold = 0.55
    max_vector_size = 8
    amt_reid = 2000