[embedding]
    json  = "/Users/load/code/python/model/model-y1-test2/model-symbol.json"
    param = "/Users/load/code/python/model/model-y1-test2/model-0000.params"
    infer_mode = "service"
    url = "http://172.19.0.15:81/r100/predict"
[age]
    json  = "/Users/load/code/python/model/gamodel-r50/model-symbol.json"
    param = "/Users/load/code/python/model/gamodel-r50/model-0000.params"
    infer_mode = "service"
    url = "http://172.19.0.15:81/ga/predict" 
    n_age_sample = 2
    enable = true   
[shape]
    width   = 112
    height  = 112
    channel = 3
    output_feature  = 128
[vector]
    sim_threshold = 0.4
    merge_threshold = 0.8
    append_threshold = 0.55
    max_vector_size = 6
    amt_reid = 2000